// Generated by CoffeeScript 1.7.1
(function() {
  var DISPLAY_HEIGHT, DISPLAY_WIDTH, Player, RootMap, checkPosition, core, map,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  DISPLAY_WIDTH = 304;

  DISPLAY_HEIGHT = 320;

  enchant();

  core = {};

  map = {};

  Player = (function(_super) {
    __extends(Player, _super);

    function Player(options) {
      this.tohou = ["marisa", "reimu", "sanae", "sakuya"];
      this.chara = options.chara;
      switch (this.chara) {
        case "miku":
          Player.__super__.constructor.call(this, 33, 32);
          this.image = core.assets['./img/chara/miku.png'];
          break;
        case "honoka":
          Player.__super__.constructor.call(this, 31, 37);
          this.image = core.assets['./img/chara/honoka.png'];
          break;
        case "kotori":
          Player.__super__.constructor.call(this, 32, 37);
          this.image = core.assets['./img/chara/kotori.png'];
          break;
        case "umi":
          Player.__super__.constructor.call(this, 32, 37);
          this.image = core.assets['./img/chara/umi.png'];
          break;
        case "eri":
          Player.__super__.constructor.call(this, 37, 37);
          this.image = core.assets['./img/chara/eri.png'];
          break;
        case "nozomi":
          Player.__super__.constructor.call(this, 37, 37);
          this.image = core.assets['./img/chara/nozomi.png'];
          break;
        case "nico":
          Player.__super__.constructor.call(this, 37, 37);
          this.image = core.assets['./img/chara/nico.png'];
          break;
        case "rin":
          Player.__super__.constructor.call(this, 29, 36);
          this.image = core.assets['./img/chara/rin.png'];
          break;
        case "hanayo":
          Player.__super__.constructor.call(this, 29, 36);
          this.image = core.assets['./img/chara/hanayo.png'];
          break;
        case "kayo":
          Player.__super__.constructor.call(this, 29, 36);
          this.image = core.assets['./img/chara/kayo.png'];
          break;
        case "maki":
          Player.__super__.constructor.call(this, 29, 36);
          this.image = core.assets['./img/chara/maki.png'];
          break;
        case "reimu":
          Player.__super__.constructor.call(this, 32, 32);
          this.image = core.assets['./img/chara/reimu.png'];
          break;
        case "marisa":
          Player.__super__.constructor.call(this, 32, 32);
          this.image = core.assets['./img/chara/marisa.png'];
          break;
        case "sanae":
          Player.__super__.constructor.call(this, 32, 32);
          this.image = core.assets['./img/chara/sanae.png'];
          break;
        case "sakuya":
          Player.__super__.constructor.call(this, 32, 32);
          this.image = core.assets['./img/chara/sakuya.png'];
          break;
      }
      this.frame = 0;
      this.tick = 0;
      this.x = 120;
      this.y = 120;
      this.state = '';
    }

    Player.prototype.isTohou = function() {
      return this.tohou.indexOf(this.chara) !== -1;
    };

    Player.prototype.onenterframe = function() {
      if (core.input.down) {
        this.state = 'down';
        this.frame = this.tick % 2 * 2;
        this.tick++;
        this.y += 4;
        checkPosition(this.x, this.y);
        if (map.hitTest(this.x + 15, this.y + 32)) {
          return this.y -= 4;
        }
      } else if (core.input.left) {
        if (this.isTohou()) {
          this.frame = this.tick % 3 + 3;
        } else {
          this.frame = this.tick % 2 * 2 + 3;
        }
        this.state = 'left';
        this.tick++;
        this.x -= 4;
        checkPosition(this.x, this.y);
        if (map.hitTest(this.x + 4, this.y + 29)) {
          return this.x += 4;
        }
      } else if (core.input.right) {
        if (this.isTohou()) {
          this.frame = this.tick % 3 + 6;
        } else {
          this.frame = this.tick % 2 * 2 + 6;
        }
        this.state = 'right';
        this.tick++;
        this.x += 4;
        checkPosition(this.x, this.y);
        if (map.hitTest(this.x + 20, this.y + 29)) {
          return this.x -= 4;
        }
      } else if (core.input.up) {
        this.y -= 4;
        if (map.hitTest(this.x + 15, this.y + 25)) {
          this.y += 4;
        }
        this.state = 'up';
        this.frame = this.tick % 2 * 2 + 9;
        this.tick++;
        return checkPosition(this.x, this.y);
      } else {
        switch (this.state) {
          case 'down':
            this.frame = 1;
            break;
          case 'left':
            this.frame = 4;
            break;
          case 'right':
            this.frame = 7;
            break;
          case 'up':
            this.frame = 10;
            break;
        }
      }
    };

    return Player;

  })(Sprite);

  RootMap = (function(_super) {
    __extends(RootMap, _super);

    function RootMap() {
      var collision, mapArray;
      RootMap.__super__.constructor.call(this, 16, 16);
      this.image = core.assets['./img/map/map1.png'];
      mapArray = [[166, 166, 166, 166, 166, 166, 166, 166, 166, 166, 166, 166, 166, 166, 166, 166, 166, 166, 166], [166, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11, 8, 8, 8, 8, 8, 8, 8, 166], [166, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11, 8, 8, 8, 8, 8, 8, 8, 166], [166, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11, 8, 8, 8, 8, 8, 8, 8, 166], [166, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11, 8, 8, 8, 8, 8, 8, 8, 166], [166, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11, 8, 8, 8, 8, 8, 8, 8, 166], [166, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11, 8, 8, 8, 8, 8, 8, 8, 166], [166, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11, 8, 8, 8, 8, 8, 8, 8, 166], [166, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11, 8, 8, 8, 8, 8, 8, 8, 166], [166, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11, 8, 8, 8, 8, 8, 8, 8, 166], [166, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11, 8, 8, 8, 8, 8, 8, 8, 166], [166, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11, 8, 8, 8, 8, 8, 8, 8, 166], [166, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11, 8, 8, 8, 8, 8, 8, 8, 166], [166, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11, 8, 8, 8, 8, 8, 8, 8, 166], [166, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11, 8, 8, 8, 8, 8, 8, 8, 166], [166, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11, 8, 8, 8, 8, 8, 8, 8, 166], [166, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11, 8, 8, 8, 8, 8, 8, 8, 166], [166, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11, 8, 8, 8, 8, 8, 8, 8, 166], [166, 8, 8, 8, 8, 8, 8, 8, 11, 11, 11, 8, 8, 8, 8, 8, 8, 8, 166], [166, 166, 166, 166, 166, 166, 166, 166, 11, 11, 11, 166, 166, 166, 166, 166, 166, 166, 166]];
      collision = [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1]];
      this.loadData(mapArray);
      this.collisionData = collision;
    }

    return RootMap;

  })(Map);

  checkPosition = function(x, y) {
    return console.log("x=" + x + ",y=" + y);
  };

  window.onload = function() {
    var assets;
    core = new Core(DISPLAY_WIDTH, DISPLAY_HEIGHT);
    core.fps = 24;
    assets = [];
    assets.push('./img/chara/miku.png');
    assets.push('./img/chara/honoka.png');
    assets.push('./img/chara/kotori.png');
    assets.push('./img/chara/umi.png');
    assets.push('./img/chara/eri.png');
    assets.push('./img/chara/nozomi.png');
    assets.push('./img/chara/nico.png');
    assets.push('./img/chara/rin.png');
    assets.push('./img/chara/hanayo.png');
    assets.push('./img/chara/kayo.png');
    assets.push('./img/chara/maki.png');
    assets.push('./img/chara/tohou.png');
    assets.push('./img/chara/reimu.png');
    assets.push('./img/chara/marisa.png');
    assets.push('./img/chara/sanae.png');
    assets.push('./img/chara/sakuya.png');
    assets.push('./img/map/map1.png');
    core.preload(assets);
    core.onload = function() {
      this.player = new Player({
        chara: "reimu"
      });
      this.map = new RootMap();
      this.pad = new Pad();
      this.pad.x = 192;
      this.pad.y = 210;
      map = this.map;
      core.rootScene.addChild(map);
      core.rootScene.addChild(this.player);
      return core.rootScene.addChild(this.pad);
    };
    return core.start();
  };

}).call(this);
