// Generated by CoffeeScript 1.7.1
(function() {
  var DISPLAY_HEIGHT, DISPLAY_WIDTH, Player, core,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  DISPLAY_WIDTH = 320;

  DISPLAY_HEIGHT = 320;

  enchant();

  core = {};

  Player = (function(_super) {
    __extends(Player, _super);

    function Player() {
      Player.__super__.constructor.call(this, 33, 32);
      this.image = core.assets['./img/chara/miku.png'];
      this.frame = 0;
      this.x = 120;
      this.y = 120;
    }

    return Player;

  })(Sprite);

  window.onload = function() {
    var assets;
    core = new Core(DISPLAY_WIDTH, DISPLAY_HEIGHT);
    core.fps = 10;
    assets = [];
    assets.push('./img/chara/miku.png');
    core.preload(assets);
    core.onload = function() {
      this.player = new Player();
      return core.rootScene.addChild(this.player);
    };
    return core.start();
  };

}).call(this);
